### PR TITLE
georeferencing cursor from image Exif

### PR DESCRIPTION
**Pull request by s-leger**
Hi,
Could be usefull for camera matching.
This operator ask for a image file, read GPS from exif and georeference cursor according.
Note : requires PIL

Usage :
On fully referenced scene, invoke the operator and pick image file with exif on it.

### CODE REVIEW

**Comment by kikislater** [comment]
Awesome, it is for photogrammetry purpose ! Should be very very interesting

**Comment by domlysz** [comment]
The idea is really cool and very useful for photomatching in archiviz like representing a 3d building on a real photo of the area.

But the code need more polishing before it can be merged.

It does not work for me because my test photo does not have altitude and the script does not handle that case. After forcing altitude to zero it work but the cursor is placed far away my scene because the offsets are not applied, I need to write something like this

```
geoscn = GeoScene()
try:
	bpy.context.scene.cursor_location = (x-geoscn.crsx, y-geoscn.crsy, 0)
...
```

Anyway the real issue for me is that the script depends on pillow, I know basemaps already depends on it but I want to remove this dependency in the future so I must avoid having more tools depending on it. Furthermore, the georaster import addon already use the [Tyf](https://github.com/Moustikitos/tyf) library for reading image tags on tiff file or jpeg. Tyf is shipped with BlenderGIS inside io_georaster folder, so it make sense to reuse it.

This lib is really easy to use, you can write something like this :

```
import Tyf

jpg = Tyf.open(filepath)

try:
	lon = jpg["GPSLongitude"] * jpg["GPSLongitudeRef"]
	lat = jpg["GPSLatitude"] * jpg["GPSLatitudeRef"]
	try:
		alt = jpg["GPSAltitude"]
	except:
		alt = 0
except:
	pass #no geotags
else:
	print(lon, lat, alt)
```



Another issue, your file browser allows selecting a set of files but there is only one cursor at all so we can only see the position of one unique photo at a time. It will be more useful if you just add empty objects at photos locations and name these objects like the jpeg files. So we'll be able to see the location of a set of photos and keep the reference to the file name.


Some other advices:

you need to catch the errors in main execute function in priority and properly finish the execution if an error is raised, something like

```

try:
	getexif()
except:
	self.report({'ERROR'}, "Message")
	return {'FINISHED'}
```


this script will be pretty simple and short so you can avoid using functions and put all your code in the operator execute function it will be easier to manage.

You can add this property in your operator to filter files extensions in the browser

```
    filter_glob = StringProperty(
        default = "*.jpg;*.jpeg;*.tif;*.tiff",
        options = {'HIDDEN'} )
```


because the scene must be georef you really need to check this situation at the beginning of execute function

```
scn = context.scene
geoscn = GeoScene(scn)
if not geoscn.isGeoref:
	self.report({'ERROR'}, "The scene must be georeferenced")
	return {'FINISHED'}
```

**Comment by s-leger** [comment]
Hi,
Thank you for your comments !
I'ts only a proof of feature, very quickly slapped.

Pillow is mature, and allow not only jpg and tif.
Anyway, if it can help to reduce dependency hell, i'll be happy to go without.

Witch version of Tyf is currently packed ? 
Seem you completely dropped .jpg support (or it's a recent add in Tyf) ?

For the file browser allowing multiple files, i was thinking about 3 options : create camera, create an empty, or moving the cursor.

**Comment by domlysz** [comment]
oh yeah sorry forgotten I've dropped some part for the lib, I'll update it today

pillow support lot of format but at all only jpg and tif are able to store exif

placing camera seems good idea, you can also pick up the focal and resolution from exif, but how to find the right orientation ?

**Comment by s-leger** [comment]
As for Tyf,
maybe create a lib/Tyf folder on root.
Still have an issue with my jpeg, "I/O operation on closed file" throw on .open() 

+1 for focal, but resolution is part of render properties, and having many cameras may result in conflicts between different images.
Should store those setting on camera, along with background image for render, and detect camera activation in some way to set up render according..

If by orientation you mean portrait and landcape, there's an EXIF tag that can store the orientation. Tag number 274, values are [documented here](http://www.impulseadventure.com/photo/exif-orientation.html). 

As far as i know there is currently no way to find camera orientation -rotation- in exif. (exif still dosen't make coffee)

**Comment by domlysz** [comment]
> resolution is part of render properties, and having many cameras may result in conflicts between different images.

exact forgotten this, when I was creating photomatch I was making one scene per camera and just link the original scene as background

selection_001

but image background still need to be switched manually...

Is the focal does not depends on sensor size? I'm afraid it can be hard to use it

> 
As far as i know there is currently no way to find camera orientation -rotation- in exif. (exif still dosen't make coffee)

yes I was talking about the rotation. Some time ago I was looking for solution to auto calibrate a camera inside Blender using a photo and some reference objects drawing on the aerial photo but I can't find anything usable

**Comment by s-leger** [comment]
For a first approximation we may use the "36mm equivalent" of exif. Another way is to use a camera database to store sensor sizes. (allready do this way in 3dsmax)

Having the camera position and osm data has proven to be a strong basis for matching. Maybe we should add "power lines" in default tags of osm, as pylons are good references.
Dropping osm to a dtm could also help a lot.
I've currently not found any service providing elevation data at global scale on the fly.

Did you know [blam](https://github.com/stuffmatic/blam) ?

**Comment by domlysz** [comment]
Sorry for the late, was very busy

Your code is really great, thanks & congrats!

I haven't any conflict with map viewer (this tool does not use Tyf), so I don't think the problem com from here. Anyway I'll will remove my Tyf.py file to use the updated lib.

I've made a new branch with your code and some little modif for testing (https://github.com/domlysz/BlenderGIS/commit/efa40b3a019bd2a15077a7fd79b2419142e02790). Tel me if you find any bug but for me it's ok for the merge

exif-read or pyexif libs are not able to correctly read geotags, that why I chose Tyf.

You can get image dimension with these tags in Tyf

`print(jpg['PixelXDimension'], jpg['PixelYDimension'])
`

Also if you want to browse all tags to see how there are named

```
for t in jpg.exif.tags():
	print(t.tag, t.key, t.value, t.meaning)
```


There is also some image utilities here to get dimensions from common images formats

https://github.com/domlysz/BlenderGIS/blob/master/utils/img.py

**Comment by s-leger** [comment]
I'll try this new branch this night, realy hoping blender won't crash.
So stay tuned !

What about Z ?
London under CH1903-LV03 (epsg:21781) is near 3m under sea level !
I think proj4 does take account of z, when ellipsoids are differents. 
And so wgs84 Altitudes should be transformed according to fit any local CSR.

**Comment by s-leger** [comment]
Ok, 
Blender crash when using map viewer. 

But narrowed down the issue. 
Tyf does override PIL Image class, don't know why since the Image class is not in use inside Tyf.
So removing the Image class override definition make it working like a charm.
see [pull request 44](https://github.com/domlysz/BlenderGIS/pull/44)

**Comment by domlysz** [comment]
Great ! I don't really understand how this PIL override part works at all, I was removing all this block in my first distibution, I think you can also remove all not only the Image class, we want a pure python lib not a pillow wrap !

So if it's ok for you I'll merge the branch

I'm currently working to regroup all the panels with some icons, now there is too many panels with just one button...

About the Z, I know I skip the reprojection of this component, I think for most of case it's not a problem. After all, when you reproject a DEM for example, pixels altitude values still remains the same. I must admit I chose to avoid Z reprojection because I was afraid to get weird values. Also most of modern datum are now using GRS80 ellps to be compatible with WGS84/GPS, especially in Europe given the INSPIRE Directive.

**Comment by s-leger** [comment]
It's ok for me, let's go !

Still left to add the "photo matching helper" panel for cameras, using defined custom props to make camera active, setting background and render resolution, but keep this for a next release.

**Pull request merged**
