### PR TITLE
bgis_utils.py for blender4

### PR DESCRIPTION
**Pull request by airtraxx**

### CODE REVIEW

**Review by UnboundGodz — CHANGES_REQUESTED** [review]
Resolved the exporting issues within Blender 4.0

**Comment by dstuessy** [comment]
Manually patching the release on my machine with those changes worked for me 👍

**Comment by HexaPulsar** [comment]
This fixed the issue.

**Comment by janbuijs91** [comment]
Editing this line in the code resolved the error I was getting. Nice!

**Comment by temeddix** [comment]
The bad news here is that this repository has not been maintained for more than a year and a half. Should somebody make a fork and make this project go forward? If so, I will be happy to manage the task.

**Comment by cmorierroy** [comment]
@dstuessy > Manually patching the release on my machine with those changes worked for me 👍

What were your steps for patching it? I'm downloading the ZIP, extracting, modifying the line, re-zipping, then trying to install in Blender, but it won't install. No error messages, just no new add-on after install.

**Comment by cmorierroy** [comment]
In the meantime, my workaround was to [install Blender 3.6.](https://download.blender.org/release/Blender3.6/) 
You can have both 4 and 3.6 at the same time, just shows up as a different app. The export works fine in 3.6.

**Comment by Lisadgold** [comment]
BINGO - Found the issue giving all the errors!!!  And it has nothing to do with using an older or brand new version of Blender.  When I copied and pasted the Opentopography API code into the SRTM area to get the elevation, I did not notice it had an empty space all the way to the left.  After I deleted the non visible space in the code it worked fine in all new and old versions of Blender.  

Making sure the API code was all the way to the left was the fix on mac and pc
code left
........ but for others with issues - it would be SUPER nice if someone would share the info on (Manually patching the release) in a step by step for the fix since everyone is having similar issues?

**Review by statulr — APPROVED** [review]
Looks great to me!

**Review by Kimu-Nowchira — APPROVED** [review]
LGTM!
It works for me. I want the producer to merge this PR, or I want someone to fork this neglected project.

**Comment by temeddix** [comment]
Yeah, I believe @domlysz should at least assign co-maintainers...

**Comment by statulr** [comment]
> LGTM! It works for me. I want the producer to merge this PR, or I want someone to fork this neglected project.

if I forked would y'all support it? caus I can👀

**Comment by temeddix** [comment]
I'll be happy to do so :)

**Comment by statulr** [comment]
> I'll be happy to do so :)

alright, i'd have to figure out the copyright situation first and then I can fork it bc I don't wanna get in legal trouble

**Comment by temeddix** [comment]
I've seen #850, but the new release has not been made since..

**Comment by tzioup** [comment]
Just downloaded BlenderGIS and experienced the same issue with exporting

I opened the relevant Python file and found that the relevant lines had been updated with an IF version >3 THEN use same code lines as listed in this thread (OR use previous code)

But it doesn't work.

I tried removing the IF and OR, saved the file, rezipped, but when I try to install in Blender the addon doesn't appear.

Quid?

Blender 4.1

**Comment by domlysz** [comment]
thx that's fixed now, sorry for the delay

**Pull request closed without merging**
