### PR TITLE
add opentopography.org api key to settings

### PR DESCRIPTION
**Pull request by lobnico**

### CODE REVIEW

**Comment by sashaman** [comment]
nice one 👍🏼

**Comment by ArsenHere** [comment]
so how do you do it??

**Comment by Waffle1434** [comment]
Worked, you have to create an account at https://portal.opentopography.org/ and hit request an API key, then paste the key in the addon settings page

**Comment by Piotr89waYT** [comment]
Hey, Could you explain how to do this? I tried it and it broke... Or add some instructions because my bran does not understand

**Comment by KeyOfCode** [comment]
I got the API Key, but now what? Where do I put it in so it can work?

**Comment by lobnico** [comment]
Since author haven t responded to pull request, u can use my fork on https://github.com/lobnico/BlenderGIS, u ll be able to insert API keys in addon settings

**Comment by nic0711** [comment]
@lobnico I would love to do so... but MAC isn't supported since 2.83. :(

**Review by tdung — APPROVED** [review]

**Comment by domlysz** [comment]
finally take the time to review and merge it, thank you !

**Pull request merged**
